apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: item-mysql-pod
  name: item-mysql-pod
spec:
  containers:
  - image: mysql
    name: item-mysql-pod
    envFrom:
      - configMapRef:
          name: sql-configs
      - secretRef:
          name: sql-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


#MYSQL_USER: root