#version: "3.1"
#services:
#  app:
#    container_name: spring-app
#    image: app
##    build: .
#    ports:
#      - 8181:8181
#    environment:
#      MYSQL_HOST: db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_PORT: 3306
#  itemmenu:
#    container_name: itemmenu
#    image: itemmenu
##    build: .
#    ports:
#      - 8282:8282
#    environment:
#      MYSQL_HOST: db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_PORT: 3306
#
#  db:
#    container_name: db
#    image: mysql
#    volumes:
#      -  /home/user/Desktop/db:/var/lib/mysq
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root 
#      MYSQL_DATABSASE: springboot

services: 
  springboot-app:
    container_name: spring-app
    image: springbooot-app
    volumes:
      -  wwwe:/var/lib/mysql
    build: .
    ports:
      - 8181:8181
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb

  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
#      -  /home/user/Desktop/db:/var/lib/mysql
      -  wwwe:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: springboot
      MYSQL_ROOT_PASSWORD: root
volumes:
  wwwe:
    external: true

